export const products = [
  { id: 1, name: 'Яблоко', category: 'Фрукты и ягоды', ageGroup: 'от 4 месяцев' },
  { id: 2, name: 'Груша', category: 'Фрукты и ягоды', ageGroup: 'от 4 месяцев' },
  { id: 3, name: 'Чернослив', category: 'Фрукты и ягоды', ageGroup: 'от 4 месяцев' },
  { id: 4, name: 'Абрикос', category: 'Фрукты и ягоды', ageGroup: 'от 7 месяцев' },
  { id: 5, name: 'Слива', category: 'Фрукты и ягоды', ageGroup: 'от 7 месяцев' },
  { id: 6, name: 'Банан', category: 'Фрукты и ягоды', ageGroup: 'от 7 месяцев' },
  { id: 7, name: 'Шиповник', category: 'Фрукты и ягоды', ageGroup: 'от 7 месяцев' },
  { id: 8, name: 'Персик', category: 'Фрукты и ягоды', ageGroup: 'от 7 месяцев' },
  { id: 9, name: 'Черника', category: 'Фрукты и ягоды', ageGroup: 'от 7 месяцев' },
  { id: 10, name: 'Вишня', category: 'Фрукты и ягоды', ageGroup: 'от 7 месяцев' },
  { id: 11, name: 'Ежевика', category: 'Фрукты и ягоды', ageGroup: 'от 9 месяцев' },
  { id: 12, name: 'Инжир', category: 'Фрукты и ягоды', ageGroup: 'от 9 месяцев' },
  { id: 13, name: 'Нектарин', category: 'Фрукты и ягоды', ageGroup: 'от 9 месяцев' },
  { id: 14, name: 'Крыжовник', category: 'Фрукты и ягоды', ageGroup: 'от 9 месяцев' },
  { id: 15, name: 'Земляника', category: 'Фрукты и ягоды', ageGroup: 'от 9 месяцев' },
  { id: 16, name: 'Клубника', category: 'Фрукты и ягоды', ageGroup: 'от 9 месяцев' },
  { id: 17, name: 'Жимолость', category: 'Фрукты и ягоды', ageGroup: 'от 9 месяцев' },
  { id: 18, name: 'Черешня', category: 'Фрукты и ягоды', ageGroup: 'от 9 месяцев' },
  { id: 19, name: 'Ананас', category: 'Фрукты и ягоды', ageGroup: 'от 12 месяцев' },
  { id: 20, name: 'Апельсин', category: 'Фрукты и ягоды', ageGroup: 'от 12 месяцев' },
  { id: 21, name: 'Дыня', category: 'Фрукты и ягоды', ageGroup: 'от 12 месяцев' },
  { id: 22, name: 'Грейпфрут', category: 'Фрукты и ягоды', ageGroup: 'от 12 месяцев' },
  { id: 23, name: 'Киви', category: 'Фрукты и ягоды', ageGroup: 'от 12 месяцев' },
  { id: 24, name: 'Лимон', category: 'Фрукты и ягоды', ageGroup: 'от 12 месяцев' },
  { id: 25, name: 'Лайм', category: 'Фрукты и ягоды', ageGroup: 'от 12 месяцев' },
  { id: 26, name: 'Мандарин', category: 'Фрукты и ягоды', ageGroup: 'от 12 месяцев' },
  { id: 27, name: 'Помело', category: 'Фрукты и ягоды', ageGroup: 'от 12 месяцев' },
  { id: 28, name: 'Хурма', category: 'Фрукты и ягоды', ageGroup: 'от 12 месяцев' },
  { id: 29, name: 'Гранат', category: 'Фрукты и ягоды', ageGroup: 'от 12 месяцев' },
  { id: 30, name: 'Арбуз', category: 'Фрукты и ягоды', ageGroup: 'от 12 месяцев' },
  { id: 31, name: 'Виноград', category: 'Фрукты и ягоды', ageGroup: 'от 12 месяцев' },
  { id: 32, name: 'Брусника', category: 'Фрукты и ягоды', ageGroup: 'от 12 месяцев' },
  { id: 33, name: 'Голубика', category: 'Фрукты и ягоды', ageGroup: 'от 12 месяцев' },
  { id: 34, name: 'Клюква', category: 'Фрукты и ягоды', ageGroup: 'от 12 месяцев' },
  { id: 35, name: 'Смородина', category: 'Фрукты и ягоды', ageGroup: 'от 12 месяцев' },
  { id: 36, name: 'Малина', category: 'Фрукты и ягоды', ageGroup: 'от 12 месяцев' },
  { id: 37, name: 'Облепиха', category: 'Фрукты и ягоды', ageGroup: 'от 12 месяцев' },
  { id: 38, name: 'Манго', category: 'Фрукты и ягоды', ageGroup: 'от 12 месяцев' },
  { id: 39, name: 'Брокколи', category: 'Овощи и зелень', ageGroup: 'от 4 месяцев' },
  { id: 40, name: 'Кабачок', category: 'Овощи и зелень', ageGroup: 'от 4 месяцев' },
  { id: 41, name: 'Цветная капуста', category: 'Овощи и зелень', ageGroup: 'от 4 месяцев' },
  { id: 42, name: 'Тыква', category: 'Овощи и зелень', ageGroup: 'от 4 месяцев' },
  { id: 43, name: 'Морковь', category: 'Овощи и зелень', ageGroup: 'от 4 месяцев' },
  { id: 44, name: 'Картофель', category: 'Овощи и зелень', ageGroup: 'от 4 месяцев' },
  { id: 45, name: 'Капуста белокочанная', category: 'Овощи и зелень', ageGroup: 'от 7 месяцев' },
  { id: 46, name: 'Стручковая фасоль', category: 'Овощи и зелень', ageGroup: 'от 7 месяцев' },
  { id: 47, name: 'Баклажан', category: 'Овощи и зелень', ageGroup: 'от 7 месяцев' },
  { id: 48, name: 'Зеленый горошек', category: 'Овощи и зелень', ageGroup: 'от 7 месяцев' },
  { id: 49, name: 'Петрушка', category: 'Овощи и зелень', ageGroup: 'от 7 месяцев' },
  { id: 50, name: 'Помидор', category: 'Овощи и зелень', ageGroup: 'от 7 месяцев' },
  { id: 51, name: 'Перец сладкий', category: 'Овощи и зелень', ageGroup: 'от 7 месяцев' },
  { id: 52, name: 'Укроп', category: 'Овощи и зелень', ageGroup: 'от 7 месяцев' },
  { id: 53, name: 'Шпинат', category: 'Овощи и зелень', ageGroup: 'от 7 месяцев' },
  { id: 54, name: 'Свекла', category: 'Овощи и зелень', ageGroup: 'от 7 месяцев' },
  { id: 55, name: 'Ревень', category: 'Овощи и зелень', ageGroup: 'от 7 месяцев' },
  { id: 56, name: 'Кукуруза', category: 'Овощи и зелень', ageGroup: 'от 12 месяцев' },
  { id: 57, name: 'Лук', category: 'Овощи и зелень', ageGroup: 'от 12 месяцев' },
  { id: 58, name: 'Кинза', category: 'Овощи и зелень', ageGroup: 'от 12 месяцев' },
  { id: 59, name: 'Огурец', category: 'Овощи и зелень', ageGroup: 'от 12 месяцев' },
  { id: 60, name: 'Редис', category: 'Овощи и зелень', ageGroup: 'от 12 месяцев' },
  { id: 61, name: 'Чеснок', category: 'Овощи и зелень', ageGroup: 'от 12 месяцев' },
  { id: 62, name: 'Кролик', category: 'Белки', ageGroup: 'от 6 месяцев' },
  { id: 63, name: 'Индейка', category: 'Белки', ageGroup: 'от 6 месяцев' },
  { id: 64, name: 'Говядина', category: 'Белки', ageGroup: 'от 6 месяцев' },
  { id: 65, name: 'Телятина', category: 'Белки', ageGroup: 'от 6 месяцев' },
  { id: 66, name: 'Перепелка', category: 'Белки', ageGroup: 'от 6 месяцев' },
  { id: 67, name: 'Курица', category: 'Белки', ageGroup: 'от 6 месяцев' },
  { id: 68, name: 'Кефир', category: 'Белки', ageGroup: 'от 8 месяцев' },
  { id: 69, name: 'Биолакт', category: 'Белки', ageGroup: 'от 8 месяцев' },
  { id: 70, name: 'Творог', category: 'Белки', ageGroup: 'от 8 месяцев' },
  { id: 71, name: 'Рыба (нежирных сортов)', category: 'Белки', ageGroup: 'от 8 месяцев' },
  { id: 72, name: 'Печень (говяжья)', category: 'Белки', ageGroup: 'от 8 месяцев' },
  { id: 73, name: 'Печень (куриная)', category: 'Белки', ageGroup: 'от 8 месяцев' },
  { id: 74, name: 'Рыба морская (красная)', category: 'Белки', ageGroup: 'от 12 месяцев' },
  { id: 75, name: 'Баранина', category: 'Белки', ageGroup: 'от 12 месяцев' },
  { id: 76, name: 'Субпродукты', category: 'Белки', ageGroup: 'от 12 месяцев' },
  { id: 77, name: 'Молоко', category: 'Белки', ageGroup: 'от 12 месяцев' },
  { id: 78, name: 'Свинина', category: 'Белки', ageGroup: 'от 12 месяцев' },
  { id: 79, name: 'Сыр', category: 'Белки', ageGroup: 'от 12 месяцев' },
  { id: 80, name: 'Креветки', category: 'Белки', ageGroup: 'от 36 месяцев' },
  { id: 81, name: 'Кальмар', category: 'Белки', ageGroup: 'от 36 месяцев' },
  { id: 82, name: 'Мидии', category: 'Белки', ageGroup: 'от 36 месяцев' },
  { id: 83, name: 'Соя', category: 'Белки', ageGroup: 'от 36 месяцев' },
  { id: 84, name: 'Грибы (белые)', category: 'Белки', ageGroup: 'от 36 месяцев' },
  { id: 85, name: 'Гречневая каша', category: 'Углеводы', ageGroup: 'от 4 месяцев' },
  { id: 86, name: 'Кукурузная каша', category: 'Углеводы', ageGroup: 'от 4 месяцев' },
  { id: 87, name: 'Рисовая каша', category: 'Углеводы', ageGroup: 'от 4 месяцев' },
  { id: 88, name: 'Овсяная каша', category: 'Углеводы', ageGroup: 'от 4 месяцев' },
  { id: 89, name: 'Мультизлаковая каша', category: 'Углеводы', ageGroup: 'от 7 месяцев' },
  { id: 90, name: 'Пшеничная каша', category: 'Углеводы', ageGroup: 'от 7 месяцев' },
  { id: 91, name: 'Ячневая каша', category: 'Углеводы', ageGroup: 'от 7 месяцев' },
  { id: 92, name: 'Хлеб', category: 'Углеводы', ageGroup: 'от 7 месяцев' },
  { id: 93, name: 'Печенье', category: 'Углеводы', ageGroup: 'от 7 месяцев' },
  { id: 94, name: 'Горох', category: 'Углеводы', ageGroup: 'от 11 месяцев' },
  { id: 95, name: 'Фасоль', category: 'Углеводы', ageGroup: 'от 11 месяцев' },
  { id: 96, name: 'Чечевица', category: 'Углеводы', ageGroup: 'от 11 месяцев' },
  { id: 97, name: 'Макароны', category: 'Углеводы', ageGroup: 'от 11 месяцев' },
  { id: 98, name: 'Булгур', category: 'Углеводы', ageGroup: 'от 24 месяцев' },
  { id: 99, name: 'Киноа', category: 'Углеводы', ageGroup: 'от 24 месяцев' },
  { id: 100, name: 'Перловая каша', category: 'Углеводы', ageGroup: 'от 24 месяцев' },
  { id: 101, name: 'Авокадо', category: 'Жиры', ageGroup: 'от 7 месяцев' },
  { id: 102, name: 'Желток яйца', category: 'Жиры', ageGroup: 'от 7 месяцев' },
  { id: 103, name: 'Оливковое масло', category: 'Жиры', ageGroup: 'от 7 месяцев' },
  { id: 104, name: 'Сливочное масло', category: 'Жиры', ageGroup: 'от 7 месяцев' },
  { id: 105, name: 'Подсолнечное масло', category: 'Жиры', ageGroup: 'от 7 месяцев' },
  { id: 106, name: 'Кукурузное масло', category: 'Жиры', ageGroup: 'от 7 месяцев' },
  { id: 107, name: 'Жирные сорта рыбы', category: 'Жиры', ageGroup: 'от 12 месяцев' },
  { id: 108, name: 'Арахис', category: 'Жиры', ageGroup: 'от 18 месяцев' },
  { id: 109, name: 'Кунжут', category: 'Жиры', ageGroup: 'от 18 месяцев' },
  { id: 110, name: 'Семена чиа', category: 'Жиры', ageGroup: 'от 18 месяцев' },
  { id: 111, name: 'Семена льна', category: 'Жиры', ageGroup: 'от 18 месяцев' },
  { id: 112, name: 'Тыквенные семена', category: 'Жиры', ageGroup: 'от 18 месяцев' },
  { id: 113, name: 'Семена подсолнечника', category: 'Жиры', ageGroup: 'от 18 месяцев' },
  { id: 114, name: 'Яйцо куриное', category: 'Аллергены', ageGroup: '' },
  { id: 115, name: 'Молоко коровье', category: 'Аллергены', ageGroup: '' },
  { id: 116, name: 'Рыба', category: 'Аллергены', ageGroup: '' },
  { id: 117, name: 'Морепродукты', category: 'Аллергены', ageGroup: '' },
  { id: 118, name: 'Помидор', category: 'Аллергены', ageGroup: '' },
  { id: 119, name: 'Арахис', category: 'Аллергены', ageGroup: '' },
  { id: 120, name: 'Орехи', category: 'Аллергены', ageGroup: '' },
  { id: 121, name: 'Соевые бобы', category: 'Аллергены', ageGroup: '' },
  { id: 122, name: 'Цитрус', category: 'Аллергены', ageGroup: '' },
  { id: 123, name: 'Клубника', category: 'Аллергены', ageGroup: '' },
  { id: 124, name: 'Мед', category: 'Аллергены', ageGroup: '' },
  { id: 125, name: 'Пшеница', category: 'Аллергены', ageGroup: '' },
];